services:
  db:
      container_name: db
      image: postgres:latest
      environment:
        POSTGRES_USER: ${POSTGRES_DB_USERNAME}
        POSTGRES_PASSWORD: ${POSTGRES_DB_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB_NAME}
      ports:
        - 5432:5432
      volumes:
        - ./postgresql:/var/lib/postgresql
        - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  api:
    container_name: file-upload-api
    build:
      context: ./
    depends_on:
      - db
    ports:
      - ${API_PORT}:${API_PORT}
      - ${WS_PORT}:${WS_PORT}
    environment:
      POSTGRES_DB_NAME: ${POSTGRES_DB_NAME}
      POSTGRES_DB_USERNAME: ${POSTGRES_DB_USERNAME}
      POSTGRES_DB_HOST: "db"
      POSTGRES_DB_PASSWORD: ${POSTGRES_DB_PASSWORD}
      POSTGRES_DB_PORT: ${POSTGRES_DB_PORT}
      WS_PORT: ${WS_PORT}
      WS_HOST: "file-upload-api"
networks:
  net:
    driver: bridge
