services:
  db:
      container_name: db
      image: postgres:latest
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: "!fileUpload123"
        POSTGRES_DB: file_upload
      ports:
        - 5432:5432
      volumes:
        - ./postgresql:/var/lib/postgresql
        - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  api:
    container_name: file-upload-api
    build:
      context: ./
    depends_on:
      - db
    ports:
      - 3001:3001
      - 8080:8080
    environment:
      POSTGRES_DB_NAME: "file_upload"
      POSTGRES_DB_USERNAME: "postgres"
      POSTGRES_DB_HOST: "db"
      POSTGRES_DB_PASSWORD: "!fileUpload123"
      POSTGRES_DB_PORT: "5432"
      WS_PORT: "8080"
      WS_HOST: "file-upload-api"
networks:
  net:
    driver: bridge
